name: "Setup Tombi"
description: "Set up your GitHub Actions workflow with a specific version of Tombi"
author: "tombi-toml"
inputs:
  version:
    description: 'Version of Tombi to install (e.g., "0.3.31", "latest")'
    required: false
  checksum:
    description: "SHA256 checksum to validate the downloaded executable"
    required: false

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "feather"
  color: "blue"
