name: Update Version
on:
  workflow_dispatch:

jobs:
  release:
    name: "Update version"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - run: git config --global user.name 'Github Actions'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - run: python3 update_version.py
