name: Update Readme Version
on:
  workflow_dispatch:

jobs:
  release:
    name: "Update readme version"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - run: git config --global user.name 'Github Actions'
      - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - run: uv run --no-project update_readme_version.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
