---
name: Update Major Minor Tags

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  update-major-minor-tags:
    name: Update major/minor tags
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update major/minor tags
        run: |
          set -eu

          cd "${GITHUB_WORKSPACE}" || exit

          git fetch origin main --tags

          TAG="${GITHUB_REF#refs/tags/}" # v1.2.3
          MINOR="${TAG%.*}"              # v1.2
          MAJOR="${MINOR%.*}"            # v1
          MESSAGE="Release ${TAG}"

          MAIN_SHA="$(git rev-parse origin/main)"
          TAG_SHA="$(git rev-list -n 1 "${TAG}")"

          if [ "${MAIN_SHA}" != "${TAG_SHA}" ]; then
            echo "Refusing to update major/minor tags: tag ${TAG} (${TAG_SHA}) does not match origin/main (${MAIN_SHA})"
            exit 1
          fi

          # Set up Git.
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Update MAJOR/MINOR tag
          git tag -fa "${MAJOR}" origin/main -m "${MESSAGE}"
          git tag -fa "${MINOR}" origin/main -m "${MESSAGE}"

          # Push
          git push --force origin "${MINOR}"
          git push --force origin "${MAJOR}"
